Repository umee-network/umee, pull requests merged in 2022-10, with the labels that each got.

#1461 chore: improve cache build
  .github/workflows/build.yml
  .github/workflows/tests.yml
  app/app.go
Labels: A:Automerge

#1442 refactor: Remove unnecessary instances of keepReconnecting
  price-feeder/CHANGELOG.md
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/kraken.go
Labels: C:x/oracle, C:Price-Feeder, S:backport/price-feeder/v1.x.x

#1445 feat(price-feeder): computed price api routes
  price-feeder/CHANGELOG.md
  price-feeder/oracle/convert.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/oracle_test.go
  price-feeder/oracle/prices.go
  price-feeder/oracle/util.go
  price-feeder/oracle/util_test.go
  price-feeder/router/v1/oracle.go
  price-feeder/router/v1/response.go
  price-feeder/router/v1/router.go
  price-feeder/router/v1/router_test.go
Labels: C:Price-Feeder

#1448 feat: Add crypto.com provider
  price-feeder/CHANGELOG.md
  price-feeder/README.md
  price-feeder/config/config.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/provider/crypto.go
  price-feeder/oracle/provider/crypto_test.go
  price-feeder/oracle/provider/provider.go
Labels: C:Price-Feeder

#1447 docs: update release procedure
  CONTRIBUTING.md
  RELEASE_NOTES.md
Labels: A:Automerge

#1481 chore: update mergify to new release scheme
  .mergify.yml
Labels: C:Tools

#1480 feat: add v3.1 upgrade handler
  app/upgrades.go
Labels: A:Automerge, C:Core

#1471 fix: slash window progress reset
  CHANGELOG.md
  x/oracle/keeper/grpc_query.go
Labels: A:Automerge, C:x/oracle

#1478 chore: bump SDK and IBC
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1479 feat: add MsgSupplyCollateral
  CHANGELOG.md
  proto/umee/leverage/v1/tx.proto
  x/leverage/client/cli/tx.go
  x/leverage/client/tests/tests.go
  x/leverage/keeper/msg_server.go
  x/leverage/types/tx.go
  x/leverage/types/tx.pb.go
Labels: C:x/leverage, A:Automerge

#1474 chore: bump GB
  CHANGELOG.md
  go.mod
  go.sum
Labels: T:Dependencies, A:Automerge

#1408 fix: buf cosmos-sdk version
  Makefile
  proto/buf.lock
Labels: T:Dependencies, C:Core

#1485 fix: update th buf cache to get proto deps
  proto/buf.yaml
Labels: A:Automerge

#1487 fix: add new msg type to codec
  x/leverage/types/codec.go
Labels: C:x/leverage, A:Automerge

#1484 refactor: Standardize websocket connection error for providers
  price-feeder/CHANGELOG.md
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/bitget.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/crypto.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/mexc.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/types/errors.go
Labels: A:Automerge, C:Price-Feeder

#1489 feat: create docker images when new tag is released
  .dockerignore
  .github/workflows/docker.yml
  .github/workflows/price-feeder-docker.yml
  .github/workflows/price-feeder-release.yml
  .github/workflows/umee-docker.yml
  contrib/images/price-feeder.Dockerfile
  contrib/images/umeed.Dockerfile
Labels: A:Automerge

#1398 feat: add binary format to releaser
  .goreleaser.yml
Labels: T:CI, A:Automerge, Enable:ReleaseBuild

#1494 docs: update price-feeder docs
  price-feeder/README.md
Labels: C:Docs, C:Price-Feeder

#1468 chore: update peer validators
  networks/umee-1/peers/node101.txt
Labels: A:Automerge

#1496 feat: Query coin gecko for available providers for a given currency
  price-feeder/CHANGELOG.md
  price-feeder/README.md
  price-feeder/cmd/price-feeder.go
  price-feeder/config/config.go
  price-feeder/config/config_test.go
  price-feeder/config/currency_provider_tracker.go
Labels: C:Price-Feeder

#1475 fix(lint): revive CI
  .github/workflows/lint.yml
  Makefile
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: A:Automerge

#1512 docs: v3.0.3 release notes
  RELEASE_NOTES.md
  price-feeder/README.md
Labels: C:Docs

#1501 fix: Dragonberry patch
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1513 feat: implement RegisterNodeService for UmeeApp
  CHANGELOG.md
  app/app.go
Labels: A:Automerge, C:Core

#1426 docs: v3.1 Release Notes
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: A:Automerge, C:Docs

#1510 feat: Integrate osmosis-api into price-feeder
  price-feeder/CHANGELOG.md
  price-feeder/README.md
  price-feeder/config/config.go
  price-feeder/config/currency_provider_tracker.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/provider/crypto.go
  price-feeder/oracle/provider/mexc.go
  price-feeder/oracle/provider/osmosisv2.go
  price-feeder/oracle/provider/osmosisv2_test.go
  price-feeder/oracle/provider/provider.go
Labels: C:Price-Feeder

#1527 feat: change funcs to public
  price-feeder/CHANGELOG.md
  price-feeder/oracle/convert.go
  price-feeder/oracle/convert_test.go
  price-feeder/oracle/oracle.go
Labels: P:Low, C:Price-Feeder

#1530 chore: Remove websocket read log
  price-feeder/oracle/provider/websocket_controller.go
Labels: C:Price-Feeder

#1528 docs: update compatibility matrix
  README.md
Labels: A:Automerge, C:Docs

#1490 chore: upgrade-test-single-node to 046 proposal type
  .gitignore
  contrib/scripts/download-mainnet-umeed.sh
  contrib/scripts/tinker-mainnet-genesis.sh
  contrib/scripts/umeemainnet_fork.sh
  contrib/scripts/upgrade-test-single-node.sh
Labels: P:Low

#1535 fix: enable revive linter in golangci
  .github/workflows/lint.yml
  .golangci.yml
  .revive.toml
  Makefile
  go.mod
  go.sum
  tools/tools.go
Labels: C:Tools

#1539 chore: update tparse
  .github/workflows/tests.yml
Labels: T:Dependencies

#1534 feat: add osmosis-api asset pairs REST endpoint
  price-feeder/CHANGELOG.md
  price-feeder/config/currency_provider_tracker.go
  price-feeder/oracle/provider/osmosisv2.go
Labels: C:Price-Feeder
