Repository umee-network/umee, pull requests merged in 2022-05, with the labels that each got.

#866 refactor: x/oracle: make GetExchangeRateBase more efficient
  CHANGELOG.md
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/grpc_query_test.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
Labels: T:Test, C:x/oracle, C:Audit, S:backport/v2.x.x

#870 chore: Move proto v1beta1 to v1
  CHANGELOG.md
  proto/umee/leverage/v1/genesis.proto
  proto/umee/leverage/v1/gov.proto
  proto/umee/leverage/v1/leverage.proto
  proto/umee/leverage/v1/query.proto
  proto/umee/leverage/v1/tx.proto
  proto/umee/oracle/v1/genesis.proto
  proto/umee/oracle/v1/oracle.proto
  proto/umee/oracle/v1/query.proto
  proto/umee/oracle/v1/tx.proto
Labels: C:x/leverage, C:API, A:Automerge, C:x/oracle, S:backport/v2.x.x

#874 chore: update state sync providers
  networks/umee-1/README.md
Labels: A:Automerge, C:Docs, S:backport/v2.x.x

#860 feat: added update-clent and IBC update proposals
  CHANGELOG.md
  app/app.go
Labels: P:High, A:Automerge, C:IBC, S:backport/v2.x.x

#877 chore: regenerate proto files
  price-feeder/go.mod
  price-feeder/go.sum
  tests/e2e/e2e_setup_test.go
  x/leverage/types/genesis.pb.go
  x/leverage/types/gov.pb.go
  x/leverage/types/leverage.pb.go
  x/leverage/types/query.pb.go
  x/leverage/types/query.pb.gw.go
  x/leverage/types/tx.pb.go
  x/oracle/types/genesis.pb.go
  x/oracle/types/oracle.pb.go
  x/oracle/types/query.pb.go
  x/oracle/types/query.pb.gw.go
  x/oracle/types/tx.pb.go
Labels: A:Automerge, S:backport/v2.x.x

#884 chore: go mod tidy --compat=1.17
  go.sum
  price-feeder/go.sum
Labels: A:Automerge, S:backport/v2.x.x, S:backport/price-feeder/v0.2.x

#889 docs: update adr template
  docs/architecture/adr-template.md
Labels: A:Automerge

#888 chore: add script to tidy all go modules
  Makefile
  contrib/scripts/go-mod-tidy-all.sh
Labels: T:Dev UX, A:Automerge

#894 feat: add MarketSummary query
  CHANGELOG.md
  proto/umee/leverage/v1/query.proto
  x/leverage/keeper/grpc_query.go
  x/leverage/spec/03_queries.md
  x/leverage/types/query.pb.go
  x/leverage/types/query.pb.gw.go
Labels: C:x/leverage, T:Performance, S:backport/v2.x.x

#901 chore: cl++
  CHANGELOG.md
Labels: A:Automerge, C:Docs, S:backport/v2.x.x

#915 chore: update release procedure
  CONTRIBUTING.md
  README.md
Labels: A:Automerge, C:Docs

#918 feat: add missing market summary CLI query
  CHANGELOG.md
  x/leverage/client/cli/query.go
Labels: C:CLI, C:x/leverage, S:backport/v2.x.x

#917 docs: contributing.md clarification
  CONTRIBUTING.md
Labels: A:Automerge, C:Docs

#913 feat: add enabled/blacklist fields to tokens
  CHANGELOG.md
  app/test_helpers.go
  proto/umee/leverage/v1/leverage.proto
  tests/e2e/e2e_setup_test.go
  x/leverage/client/tests/suite.go
  x/leverage/gov_handler.go
  x/leverage/gov_handler_test.go
  x/leverage/keeper/borrows_test.go
  x/leverage/keeper/genesis.go
  x/leverage/keeper/interest.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/reserves.go
  x/leverage/keeper/token.go
  x/leverage/simulation/operations_test.go
  x/leverage/spec/01_concepts.md
  x/leverage/spec/02_state.md
  x/leverage/types/errors.go
  x/leverage/types/leverage.pb.go
  x/leverage/types/token.go
  x/leverage/types/token_test.go
Labels: C:x/leverage, C:Audit

#927 feat: add badger db support & tune release
  .github/workflows/release.yml
  .goreleaser.yml
Labels: P:Medium, T:Performance, S:backport/v2.x.x, Enable:ReleaseBuild

#932 chore: update upstream gravity module to fix halt bug
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: C:x/peggy

#941 docs: update terra references to classic
  docs/architecture/ADR-006-oracle.md
  price-feeder/README.md
Labels: A:Automerge, C:Docs

#950 chore: price-feeder & umeed tidy
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge, C:Tools, S:backport/v2.x.x, S:backport/price-feeder/v0.2.x

#949 chore: speedup Github CI by adding more cache
  .github/workflows/build.yml
  .github/workflows/debug.yml
  .github/workflows/lint.yml
  .github/workflows/price-feeder-release.yml
  .github/workflows/release.yml
  .github/workflows/simulations.yml
  .github/workflows/tests.yml
Labels: T:CI, A:Automerge

#935 ci: Fixes protobuf linting and compliation
  .clang-format
  CHANGELOG.md
  Makefile
  buf.work.yaml
  contrib/scripts/protocgen.sh
  proto/README.md
  proto/buf.gen.gogo.yaml
  proto/buf.lock
  proto/buf.yaml
  proto/umee/leverage/v1/genesis.proto
  proto/umee/leverage/v1/leverage.proto
  proto/umee/leverage/v1/query.proto
  proto/umee/leverage/v1/tx.proto
  proto/umee/oracle/v1/genesis.proto
  proto/umee/oracle/v1/oracle.proto
  proto/umee/oracle/v1/query.proto
  proto/umee/oracle/v1/tx.proto
  x/leverage/types/genesis.pb.go
  x/leverage/types/leverage.pb.go
  x/leverage/types/tx.pb.go
  x/oracle/types/genesis.pb.go
  x/oracle/types/oracle.pb.go
  x/oracle/types/query.pb.go
Labels: P:Low, T:CI, C:Tools

#960 ci: Changing branch for breaking changes checker
  Makefile
Labels: T:CI

#962 chore: streamline AccrueAllInterest
  CHANGELOG.md
  x/leverage/keeper/interest.go
Labels: C:x/leverage, C:Audit

#959 chore: improve ModuleBalance
  CHANGELOG.md
  x/leverage/keeper/keeper.go
Labels: C:x/leverage, C:Audit

#967 fix: taylor series of exponential used for interest accrual
  CHANGELOG.md
  x/leverage/keeper/interest.go
  x/leverage/keeper/math.go
Labels: C:x/leverage, C:Audit

#969 chore: clean protocgen.sh
  contrib/scripts/protocgen.sh
Labels: A:Automerge, C:Tools

#975 chore: go 1.18
  .github/workflows/build.yml
  .github/workflows/debug.yml
  .github/workflows/lint.yml
  .github/workflows/price-feeder-release.yml
  .github/workflows/release.yml
  .github/workflows/simulations.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  contrib/scripts/go-mod-tidy-all.sh
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
  tests/e2e/docker/gaia.Dockerfile
  umee.e2e.Dockerfile
Labels: A:Automerge

#976 chore: update price feeder releaser to use 1.18
  price-feeder/.goreleaser.yml
Labels: T:CI, A:Automerge, C:x/oracle, S:backport/price-feeder/v0.2.x

#978 chore: price-feeder: oracle package cleanup
  price-feeder/CHANGELOG.md
  price-feeder/oracle/convert.go
  price-feeder/oracle/convert_test.go
  price-feeder/oracle/filter.go
  price-feeder/oracle/filter_test.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/oracle_test.go
Labels: A:Automerge, C:x/oracle, C:Tools, S:backport/price-feeder/v0.2.x

#987 perf: Streamline leverage CLI tests
  CHANGELOG.md
  x/leverage/client/cli/proposal_test.go
  x/leverage/client/cli/tx.go
  x/leverage/client/tests/suite.go
  x/leverage/client/tests/tests.go
  x/leverage/client/tests/util.go
Labels: C:x/leverage, T:Test, T:Performance
