Repository umee-network/umee, pull requests merged in 2022-08, with the labels that each got.

#1188 feat(proto)!: Condense redundant queries into market_summary
  CHANGELOG.md
  proto/umee/leverage/v1/leverage.proto
  proto/umee/leverage/v1/query.proto
  x/leverage/client/cli/query.go
  x/leverage/client/tests/tests.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/spec/03_queries.md
  x/leverage/types/query.pb.go
  x/leverage/types/query.pb.gw.go
Labels: C:x/leverage, C:API

#1187 chore: add build-no_cgo make job
  Makefile
Labels: C:Tools

#1175 chore: Add ProviderName type
  price-feeder/CHANGELOG.md
  price-feeder/cmd/price-feeder.go
  price-feeder/config/config.go
  price-feeder/config/config_test.go
  price-feeder/oracle/convert.go
  price-feeder/oracle/convert_test.go
  price-feeder/oracle/filter.go
  price-feeder/oracle/filter_test.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/oracle_test.go
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/binance_test.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/coinbase_test.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/gate_test.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/huobi_test.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/kraken_test.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/provider/okx_test.go
  price-feeder/oracle/provider/osmosis.go
  price-feeder/oracle/provider/osmosis_test.go
  price-feeder/oracle/provider/provider.go
  price-feeder/oracle/types/provider.go
  price-feeder/oracle/util.go
  price-feeder/oracle/util_test.go
  x/leverage/types/errors.go
Labels: C:Tools, C:Price-Feeder

#1199 feat(proto)!: aggregate queries on account address to account_balances and account_summary queries
  CHANGELOG.md
  proto/umee/leverage/v1/query.proto
  x/leverage/client/cli/query.go
  x/leverage/client/tests/tests.go
  x/leverage/keeper/collateral.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/spec/03_queries.md
  x/leverage/types/query.pb.go
  x/leverage/types/query.pb.gw.go
Labels: C:x/leverage, C:API

#1203 feat: enable swagger
  CHANGELOG.md
  Makefile
  README.md
  app/app.go
  contrib/scripts/protoc-swagger-gen.sh
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
  proto/buf.gen.swagger.yaml
  swagger/proto-config-gen.json
  swagger/swagger.go
  swagger/swagger.yaml
Labels: C:API, A:Automerge, C:Docs

#1213 chore(github ci): remove duplicated build
  .github/workflows/build.yml
Labels: T:CI, A:Automerge

#1212 feat: adding checkers util package
  CHANGELOG.md
  util/checkers/doc.go
  util/checkers/sign.go
  x/leverage/types/tx.go
  x/oracle/types/msgs.go
Labels: T:Dev UX, A:Automerge

#1215 chore: ProviderName to Name in provider package
  price-feeder/CHANGELOG.md
  price-feeder/cmd/price-feeder.go
  price-feeder/cmd/version.go
  price-feeder/config/config.go
  price-feeder/config/config_test.go
  price-feeder/oracle/convert.go
  price-feeder/oracle/convert_test.go
  price-feeder/oracle/filter.go
  price-feeder/oracle/filter_test.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/oracle_test.go
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/provider/osmosis.go
  price-feeder/oracle/provider/provider.go
  price-feeder/oracle/types/provider.go
  price-feeder/oracle/util.go
  price-feeder/oracle/util_test.go
Labels: A:Automerge, C:Tools, C:Price-Feeder

#1118 feat!: liquidation directly rewards base assets
  CHANGELOG.md
  proto/umee/leverage/v1/tx.proto
  x/leverage/client/cli/tx.go
  x/leverage/client/tests/tests.go
  x/leverage/keeper/borrows.go
  x/leverage/keeper/filter.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/liquidate.go
  x/leverage/keeper/liquidate_test.go
  x/leverage/keeper/msg_server.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/oracle_test.go
  x/leverage/keeper/token.go
  x/leverage/keeper/validate.go
  x/leverage/simulation/operations.go
  x/leverage/simulation/operations_test.go
  x/leverage/spec/04_messages.md
  x/leverage/types/errors.go
  x/leverage/types/events.go
  x/leverage/types/token.go
  x/leverage/types/tx.go
  x/leverage/types/tx.pb.go
Labels: C:x/leverage, C:API, A:Automerge

#1220 feat(oracle): cli commands for prevoting / voting
  CHANGELOG.md
  x/oracle/client/cli/tx.go
Labels: C:CLI, C:x/oracle

#1221 chore(ci): update github lint and cache workflow
  .github/workflows/build.yml
  .github/workflows/debug.yml
  .github/workflows/lint.yml
  .github/workflows/price-feeder-release.yml
  .github/workflows/proto.yml
  .github/workflows/release.yml
  .github/workflows/simulations.yml
  .github/workflows/tests.yml
  .golangci.yml
  Makefile
  ante/spam_prevention.go
  cmd/umeed/cmd/debug.go
  cmd/umeed/cmd/genaccounts.go
  cmd/umeed/cmd/root.go
  go.mod
  price-feeder/oracle/oracle.go
  util/checkers/sign.go
  x/leverage/client/cli/proposal.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/liquidate.go
  x/oracle/simulations/operations.go
  x/oracle/types/errors.go
Labels: T:CI, A:Automerge

#1231 docs: cleanup todo comments
  x/leverage/keeper/interest.go
  x/leverage/module.go
Labels: A:Automerge

#1235 fix: make lint OSX compatibility
  Makefile
  price-feeder/Makefile
Labels: C:Tools

#1228 feat(leverage): token supply limit
  app/test_helpers.go
  proto/umee/leverage/v1/leverage.proto
  starport.ci.yml
  tests/e2e/e2e_setup_test.go
  x/leverage/client/tests/tests.go
  x/leverage/fixtures/doc.go
  x/leverage/fixtures/token.go
  x/leverage/gov_handler_test.go
  x/leverage/keeper/keeper_test.go
  x/leverage/simulation/operations_test.go
  x/leverage/types/leverage.pb.go
  x/leverage/types/token.go
  x/leverage/types/token_test.go
Labels: C:x/leverage, C:API, A:Automerge

#1222 feat: Add DirectLiquidationFee and uToken liquidation option
  CHANGELOG.md
  proto/umee/leverage/v1/leverage.proto
  proto/umee/leverage/v1/tx.proto
  swagger/swagger.yaml
  x/leverage/client/tests/tests.go
  x/leverage/keeper/borrows.go
  x/leverage/keeper/borrows_test.go
  x/leverage/keeper/collateral.go
  x/leverage/keeper/collateral_test.go
  x/leverage/keeper/exchange_rate.go
  x/leverage/keeper/filter.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/keeper/iter.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/liquidate.go
  x/leverage/keeper/reserves.go
  x/leverage/keeper/store.go
  x/leverage/keeper/supply.go
  x/leverage/keeper/token.go
  x/leverage/keeper/validate.go
  x/leverage/simulation/genesis.go
  x/leverage/simulation/operations.go
  x/leverage/simulation/operations_test.go
  x/leverage/simulation/params.go
  x/leverage/spec/07_params.md
  x/leverage/types/errors.go
  x/leverage/types/leverage.pb.go
  x/leverage/types/params.go
  x/leverage/types/token.go
  x/leverage/types/token_test.go
  x/leverage/types/tx.pb.go
Labels: C:x/leverage, C:API, A:Automerge

#1238 feat: add bad debt query
  CHANGELOG.md
  proto/umee/leverage/v1/query.proto
  proto/umee/leverage/v1/tx.proto
  x/leverage/keeper/grpc_query.go
  x/leverage/spec/03_queries.md
  x/leverage/types/query.pb.go
  x/leverage/types/query.pb.gw.go
Labels: C:x/leverage, C:API

#1229 fix: HAL-05 Unhandled Errors
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/types/errors.go
Labels: C:Audit, C:Price-Feeder

#1236 feat!: Add informative response fields for leverage messages
  CHANGELOG.md
  Makefile
  proto/umee/leverage/v1/tx.proto
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/msg_server.go
  x/leverage/simulation/operations.go
  x/leverage/simulation/operations_test.go
  x/leverage/types/events.go
  x/leverage/types/tx.go
  x/leverage/types/tx.pb.go
Labels: C:x/leverage, C:API

#1237 style: cosmetic cleanups
  proto/umee/leverage/v1/leverage.proto
  x/leverage/keeper/collateral.go
  x/leverage/keeper/keeper.go
  x/leverage/types/leverage.pb.go
Labels: C:x/leverage

#1244 fix: add verification to conversionRates
  price-feeder/CHANGELOG.md
  price-feeder/oracle/convert.go
Labels: C:Price-Feeder

#1243 chore: WIP HAL-07 use the html/template package #1195
  price-feeder/router/v1/response.go
  price-feeder/router/v1/router.go
Labels: A:Automerge, C:Audit, C:Price-Feeder

#1248 feat(ci): add dependencies review check
  .github/workflows/dependencies-review.yml
Labels: T:Security, T:CI, A:Automerge

#1249 feat(ci): add markdown link checker
  .github/workflows/linkchecker.yml
Labels: T:CI, A:Automerge

#1250 chore(ci): add event file filters to workflows
  .github/workflows/proto.yml
Labels: T:CI, A:Automerge

#1247 feat(ci): add codeql checks
  .github/workflows/codeql-analysis.yml
Labels: T:CI, A:Automerge, C:Tools

#1255 refactor(price-feeder): Move TickerPrice and CandlePrice to types package
  price-feeder/CHANGELOG.md
  price-feeder/oracle/convert.go
  price-feeder/oracle/convert_test.go
  price-feeder/oracle/filter.go
  price-feeder/oracle/filter_test.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/oracle_test.go
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/kraken_test.go
  price-feeder/oracle/provider/mock.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/provider/osmosis.go
  price-feeder/oracle/provider/provider.go
  price-feeder/oracle/types/candle_price.go
  price-feeder/oracle/types/candle_price_test.go
  price-feeder/oracle/types/ticker_price.go
  price-feeder/oracle/types/ticker_price_test.go
  price-feeder/oracle/util_test.go
Labels: A:Automerge, C:Price-Feeder

#1257 fix: Update package reference for MD link checker
  .github/workflows/linkchecker.yml
Labels: A:Automerge

#1258 chore: disable linting for all link-related checks
  .github/workflows/linkchecker.yml
  docs/design_docs/001-interest-stream.md
  docs/design_docs/006-oracle.md
  networks/umee-1/README.md
  price-feeder/CHANGELOG.md
  price-feeder/README.md
Labels: P:Low, T:CI, C:Tools

#1251 chore(ci): remove PR event from release workflow
  .github/workflows/release.yml
Labels: T:CI

#1264 fix(price-feeder): fix osmosis timestamp
  price-feeder/CHANGELOG.md
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/osmosis.go
  price-feeder/oracle/provider/provider.go
Labels: A:Automerge

#1268 fix(price-feeder): don't panic on empty provider candles
  price-feeder/CHANGELOG.md
  price-feeder/oracle/util.go
  price-feeder/oracle/util_test.go
Labels: T:Bug, C:Price-Feeder

#1262 fix: GetComputedPrices panic
  price-feeder/CHANGELOG.md
  price-feeder/oracle/convert.go
  price-feeder/oracle/oracle_test.go
Labels: A:Automerge, C:Tools, C:Price-Feeder

#1284 fix: use http.Status* codes
  price-feeder/oracle/provider/osmosis.go
Labels: T:Bug

#1233 chore: update backport rules
  .mergify.yml
Labels: A:Automerge

#1294 refactor(oracle): simplify window progress query
  CHANGELOG.md
  x/oracle/keeper/grpc_query.go
  x/oracle/types/query.pb.gw.go
Labels: A:Automerge, C:x/oracle

#1296 chore: go 1.19
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/debug.yml
  .github/workflows/lint.yml
  .github/workflows/price-feeder-release.yml
  .github/workflows/release.yml
  .github/workflows/simulations.yml
  .github/workflows/tests.yml
  .goreleaser.yml
  contrib/scripts/go-mod-tidy-all.sh
  go.mod
  price-feeder/go.mod
  tests/e2e/docker/gaia.Dockerfile
  umee.e2e.Dockerfile
Labels: T:CI, T:Dependencies, A:Automerge, C:Tools

#1295 feat: less strict gentx validator
  app/modules.go
Labels: A:Automerge, C:Core

#1288 fix: safeguard LastInterestTime against hard forks
  CHANGELOG.md
  x/leverage/keeper/interest.go
  x/leverage/keeper/keeper_test.go
  x/leverage/types/errors.go
Labels: T:Bug, C:x/leverage, A:Automerge

#1290 feat: compute proper tx prioritization
  ante/fee.go
  ante/fee_unit_test.go
Labels: A:Automerge

#1304 chore: migrate jwt-go dependency
  go.mod
  go.sum
Labels: T:Security, A:Automerge

#1306 fix: single node script with liveness
  .github/workflows/tests.yml
  .gitignore
  contrib/scripts/single-node.sh
  contrib/scripts/test_localnet_liveness.sh
Labels: T:CI, T:Dev UX

#1291 fix: price-feeder version
  price-feeder/CHANGELOG.md
  price-feeder/Makefile
  price-feeder/cmd/version.go
Labels: C:CLI, A:Automerge, C:Tools, C:Price-Feeder

#1301 fix: proto generator
  contrib/scripts/protocgen.sh
  proto/buf.gen.gogo.yaml
Labels: A:Automerge

#1285 feat: bump cosmos-sdk to v0.46.1
  app/app.go
  cmd/umeed/cmd/root.go
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
  tests/e2e/e2e_setup_test.go
Labels: T:Dependencies, A:Automerge

#1309 chore: remove abandoned linters
  .golangci.yml
Labels: T:CI, A:Automerge, C:Tools

#1317 chore(price-feeder): update example config
  price-feeder/price-feeder.example.toml
Labels: A:Automerge

#1292 chore: update ibc and related deps.
  app/app.go
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
  tools/tools.go
  x/ibctransfer/ibc_module.go
  x/ibctransfer/keeper/keeper.go
  x/ibctransfer/keeper/keeper_test.go
  x/ibctransfer/keeper/util_test.go
Labels: T:Dependencies, A:Automerge

#1318 fix: msg interface implementation
  x/leverage/types/tx.go
  x/oracle/simulations/operations.go
  x/oracle/types/keys.go
  x/oracle/types/msgs.go
  x/oracle/types/msgs_test.go
Labels: C:x/leverage, A:Automerge, C:x/oracle
