Repository umee-network/umee, pull requests merged in 2022-12, with the labels that each got.

#1629 chore: update the instuction for running v3.2.0 with cosmwasm
  README.md
  RELEASE_NOTES.md
Labels: A:Automerge

#1634 fix(price-feeder): add minimum candle volume
  price-feeder/oracle/util.go
Labels: S:backport/price-feeder/v2.x.x

#1636 docs: update price-feeder changelog for v2.0.1
  price-feeder/CHANGELOG.md
Labels: A:Automerge, C:Docs, C:Price-Feeder, S:backport/price-feeder/v2.x.x

#1626 docs: update canon-2 instructions
  README.md
  networks/canon-2/README.md
Labels: A:Automerge, C:Docs

#1640 fix: leverage gov proposal migrations
  app/upgrades.go
  app/upgradev3x3/gov_legacy.pb.go
  app/upgradev3x3/migrate.go
  app/upgradev3x3/proposal_legacy.go
  x/leverage/abci.go
  x/leverage/types/codec.go
  x/leverage/types/msgs.go
  x/leverage/types/proposal.go
  x/oracle/types/query.pb.go
Labels: A:Automerge

#1631 docs: update historacle API and computation docs
  docs/design_docs/011-historacle-pricing.md
Labels: A:Automerge, C:Docs, C:x/oracle

#1644 chore: remove duplicate code in tests of leverage module
  app/test_helpers.go
  tests/e2e/e2e_setup_test.go
  x/leverage/client/tests/suite.go
  x/leverage/client/tests/tests.go
Labels: A:Automerge

#1645 fix: docker build & release
  .github/workflows/price-feeder-docker.yml
  .github/workflows/umee-docker.yml
  Makefile
  contrib/images/price-feeder.dockerfile
  contrib/images/umee.e2e.dockerfile
  contrib/images/umeed.Dockerfile
  contrib/images/umeed.dockerfile
Labels: T:CI, A:Automerge

#1648 chore: make proto-all
  proto/umee/oracle/v1/genesis.proto
  proto/umee/oracle/v1/oracle.proto
Labels: A:Automerge

#1653 feat: implement incentive msg interface
  proto/umee/incentive/v1/genesis.proto
  proto/umee/oracle/v1/genesis.proto
  swagger/swagger.yaml
  util/checkers/proposal.go
  x/incentive/codec.go
  x/incentive/errors.go
  x/incentive/genesis.pb.go
  x/incentive/keys.go
  x/incentive/msgs.go
  x/incentive/params.go
  x/leverage/types/keys.go
  x/leverage/types/msgs.go
  x/oracle/types/genesis.pb.go
Labels: C:x/incentive

#1659 chore: update to Cosmos SDK 0.46.7 and related dependencies
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1660 fix: price-feeder module version
  price-feeder/CHANGELOG.md
  price-feeder/cmd/price-feeder.go
  price-feeder/config/config.go
  price-feeder/config/config_test.go
  price-feeder/go.mod
  price-feeder/main.go
  price-feeder/oracle/convert.go
  price-feeder/oracle/convert_test.go
  price-feeder/oracle/filter.go
  price-feeder/oracle/filter_test.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/oracle_test.go
  price-feeder/oracle/prices.go
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/binance_test.go
  price-feeder/oracle/provider/bitget.go
  price-feeder/oracle/provider/bitget_test.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/coinbase_test.go
  price-feeder/oracle/provider/crypto.go
  price-feeder/oracle/provider/crypto_test.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/gate_test.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/huobi_test.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/kraken_test.go
  price-feeder/oracle/provider/mexc.go
  price-feeder/oracle/provider/mexc_test.go
  price-feeder/oracle/provider/mock.go
  price-feeder/oracle/provider/mock_test.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/provider/okx_test.go
  price-feeder/oracle/provider/osmosis.go
  price-feeder/oracle/provider/osmosis_test.go
  price-feeder/oracle/provider/osmosisv2.go
  price-feeder/oracle/provider/osmosisv2_test.go
  price-feeder/oracle/provider/provider.go
  price-feeder/oracle/provider/websocket_controller.go
  price-feeder/oracle/util.go
  price-feeder/oracle/util_test.go
  price-feeder/router/middleware/middleware.go
  price-feeder/router/v1/oracle.go
  price-feeder/router/v1/response.go
  price-feeder/router/v1/router.go
  price-feeder/router/v1/router_test.go
  price-feeder/tests/integration/fixtures.go
  price-feeder/tests/integration/provider_test.go
Labels: A:Automerge, C:Price-Feeder, S:backport/price-feeder/v2.x.x

#1667 chore: bump ibc-go
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1664 fix: fix the price-feeder docker image release
  .github/workflows/price-feeder-docker.yml
  .github/workflows/umee-docker.yml
Labels: A:Automerge

#1670 chore: remove latest flavor for price-feeder docker release
  .github/workflows/price-feeder-docker.yml
  .github/workflows/price-feeder-release.yml
Labels: T:CI

#1672 fix: price-feeder and proto CI
  .github/workflows/price-feeder-docker.yml
  .github/workflows/proto.yml
  price-feeder/.goreleaser.yml
  price-feeder/LICENSE
Labels: T:CI

#1646 docs: v3.3.0 Release Notes
  CHANGELOG.md
  README.md
  RELEASE_NOTES.md
Labels: C:Docs

#1673 docs: update changelog
  CHANGELOG.md
Labels: A:Automerge, C:Docs

#1669 feat: auto kill CI workflows on update
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/debug.yml
  .github/workflows/dependencies-review.yml
  .github/workflows/linkchecker.yml
  .github/workflows/lint-pr.yml
  .github/workflows/lint.yml
  .github/workflows/price-feeder-docker.yml
  .github/workflows/price-feeder-release.yml
  .github/workflows/proto.yml
  .github/workflows/release.yml
  .github/workflows/simulations.yml
  .github/workflows/tests.yml
  .github/workflows/umee-docker.yml
  app/app.go
Labels: T:CI, A:Automerge

#1676 chore: optimize CI workflows
  .github/workflows/build.yml
  .github/workflows/lint-pr.yml
  .github/workflows/lint.yml
  .github/workflows/release-price-feeder-docker.yml
  .github/workflows/release-price-feeder.yml
  .github/workflows/release-umee-docker.yml
  .github/workflows/release-umee.yml
  .github/workflows/tests.yml
  app/app.go
Labels: T:CI, A:Automerge

#1674 feat(cli): add tests for export and import genesis
  .github/workflows/simulations.yml
  Makefile
  app/app.go
  tests/simulation/sim_test.go
  tests/simulation/state.go
Labels: T:CI, A:Automerge, T:Simulations

#1656 feat: historacle migrations for v3.3.0 -> v3.4.0
  app/upgrades.go
  x/oracle/keeper/migrations.go
  x/oracle/module.go
  x/oracle/types/params.go
Labels: A:Automerge

#1678 docs: Update RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: A:Automerge, C:Docs
