Repository umee-network/umee, pull requests merged in 2022-09, with the labels that each got.

#1300 refactor: improve leverage keeper tests and errors
  CHANGELOG.md
  app/app.go
  x/leverage/client/tests/suite.go
  x/leverage/client/tests/tests.go
  x/leverage/fixtures/token.go
  x/leverage/keeper/borrows_test.go
  x/leverage/keeper/collateral.go
  x/leverage/keeper/collateral_test.go
  x/leverage/keeper/exchange_rate.go
  x/leverage/keeper/exchange_rate_test.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/keeper/interest_test.go
  x/leverage/keeper/invariants.go
  x/leverage/keeper/invariants_test.go
  x/leverage/keeper/iter_test.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/math_test.go
  x/leverage/keeper/oracle_test.go
  x/leverage/keeper/reserves_test.go
  x/leverage/keeper/suite_test.go
  x/leverage/keeper/token.go
  x/leverage/keeper/token_test.go
  x/leverage/keeper/validate.go
  x/leverage/simulation/operations.go
  x/leverage/simulation/operations_test.go
  x/leverage/types/errors.go
  x/leverage/types/token.go
  x/leverage/types/tx.go
Labels: C:x/leverage, T:Test, T:Dev UX

#1325 fix(cli): use the correct ValAddress function for votes & prevote delegations
  x/oracle/client/cli/tx.go
Labels: T:Bug, C:CLI, A:Automerge

#1321 chore(price-feeder): update prometheus example config
  price-feeder/price-feeder.example.toml
Labels: P:Low, A:Automerge, C:Price-Feeder

#1333 fix!: Use --from flag on all leverage CLI and remove first addr argument
  CHANGELOG.md
  x/leverage/client/cli/tx.go
  x/leverage/client/tests/suite.go
  x/leverage/client/tests/tests.go
Labels: C:CLI, C:x/leverage, C:API

#1332 feat: improve EventReservesExhausted
  CHANGELOG.md
  proto/umee/leverage/v1/events.proto
  x/leverage/keeper/reserves.go
  x/leverage/types/events.pb.go
Labels: C:x/leverage, A:Automerge

#1335 fix: transfer tests
  x/ibctransfer/keeper/util_test.go
Labels: A:Automerge

#1329 feat: implement MaxCollateralShare
  CHANGELOG.md
  x/leverage/keeper/collateral.go
  x/leverage/keeper/collateral_test.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/limits.go
  x/leverage/keeper/suite_test.go
Labels: C:x/leverage, A:Automerge

#1330 feat: implement MaxSupplyUtilization
  CHANGELOG.md
  x/leverage/keeper/borrows.go
  x/leverage/keeper/borrows_test.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
Labels: C:x/leverage, A:Automerge

#1331 feat: implement MinCollateralLiquidity
  CHANGELOG.md
  x/leverage/keeper/collateral.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/limits.go
Labels: C:x/leverage

#1322 feat: improve close factor
  CHANGELOG.md
  x/leverage/keeper/collateral.go
  x/leverage/keeper/keeper_test.go
  x/leverage/keeper/liquidate.go
  x/leverage/keeper/liquidate_test.go
  x/leverage/types/token.go
Labels: C:x/leverage, A:Automerge

#1319 feat: implement MaxSupply
  CHANGELOG.md
  x/leverage/fixtures/token.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/keeper_test.go
  x/leverage/types/errors.go
Labels: C:x/leverage, A:Automerge

#1353 chore: bump gravity bridge
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1354 test: add post-cleanup queries to leverage cli test
  x/leverage/client/tests/suite.go
  x/leverage/client/tests/tests.go
Labels: C:CLI, C:x/leverage, P:Low, T:Test

#1334 feat: add CI upgrade from mainnet
  .github/workflows/tests.yml
  .gitignore
  contrib/scripts/blocks.sh
  contrib/scripts/priv_validator_key.json
  contrib/scripts/process_genesis.sh
  contrib/scripts/umeemainnet_fork.sh
  contrib/scripts/upgrade-test-single-node.sh
Labels: T:CI, T:Dev UX, A:Automerge

#1352 docs: update release matrix
  README.md
Labels: A:Automerge

#1359 fix: removed unknow field 'filter' from hermes config file
  tests/e2e/scripts/hermes_bootstrap.sh
Labels: T:CI

#1357 fix: Interpret x/0 collateral liquidity as 100%
  CHANGELOG.md
  x/leverage/keeper/collateral.go
Labels: C:x/leverage, A:Automerge

#1326 feat: setting protocol controlled min gas price
  .github/workflows/tests.yml
  .gitignore
  CHANGELOG.md
  ante/fee-notes.md
  ante/fee.go
  ante/fee_test.go
  ante/spam_prevention.go
  app/app.go
  app/modules.go
  app/params/app_settings.go
  app/params/prefix.go
  app/test_helpers.go
  cmd/umeed/cmd/app_creator.go
  cmd/umeed/cmd/debug.go
  cmd/umeed/cmd/root.go
  cmd/umeed/main.go
  contrib/scripts/blocks.sh
  contrib/scripts/process_genesis.sh
  contrib/scripts/single-node.sh
  contrib/scripts/test_localnet_liveness.sh
  contrib/scripts/umeemainnet_fork.sh
  contrib/scripts/upgrade-test-single-node.sh
  tests/e2e/e2e_setup_test.go
  tests/e2e/e2e_test.go
  tests/e2e/e2e_util_test.go
  tests/e2e/scripts/hermes_bootstrap.sh
  tests/e2e/validator.go
  tests/simulation/sim_test.go
  umee.e2e.Dockerfile
  util/coin/math.go
  util/genmap/doc.go
  util/genmap/genmap.go
  util/genmap/genmap_test.go
  util/sim/deliver.go
  x/leverage/client/tests/suite.go
  x/leverage/client/tests/tests.go
  x/leverage/keeper/exchange_rate_test.go
  x/leverage/keeper/interest_test.go
  x/leverage/keeper/invariants_test.go
  x/leverage/keeper/oracle_test.go
  x/leverage/keeper/reserves_test.go
  x/leverage/keeper/suite_test.go
  x/leverage/module.go
  x/leverage/simulation/operations.go
  x/leverage/simulation/operations_test.go
  x/leverage/types/keys_test.go
  x/oracle/client/tests/suite.go
  x/oracle/keeper/grpc_query_test.go
  x/oracle/keeper/hooks_test.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
  x/oracle/module.go
  x/oracle/simulations/operations.go
  x/oracle/types/asset.go
  x/oracle/types/expected_keeper.go
  x/oracle/types/keys_test.go
Labels: A:Automerge, C:x/oracle, C:Core

#1364 chore: remove TODO
  x/leverage/client/tests/suite.go
Labels: A:Automerge

#1365 feat: add config file to retry on HTTP 429 status code
  .github/workflows/linkchecker.config.json
  .github/workflows/linkchecker.yml
Labels: T:CI

#1363 refactor: standardize leverage KVStore getters
  CHANGELOG.md
  x/leverage/keeper/borrows.go
  x/leverage/keeper/collateral.go
  x/leverage/keeper/collateral_test.go
  x/leverage/keeper/exchange_rate.go
  x/leverage/keeper/genesis.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/interest.go
  x/leverage/keeper/internal_test.go
  x/leverage/keeper/iter.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/liquidate.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/reserves.go
  x/leverage/keeper/reserves_test.go
  x/leverage/keeper/store.go
  x/leverage/keeper/supply.go
  x/leverage/keeper/validate.go
  x/leverage/types/errors.go
Labels: C:x/leverage, P:Low

#1343 feat: automatically clear blacklisted collateral
  CHANGELOG.md
  x/leverage/keeper/filter.go
  x/leverage/keeper/iter.go
  x/leverage/keeper/reserves.go
  x/leverage/keeper/validate.go
Labels: C:x/leverage, A:Automerge

#1362 fix: for inefficient invariants, use only in tests
  CHANGELOG.md
  x/leverage/keeper/invariants.go
  x/leverage/keeper/invariants_test.go
  x/leverage/keeper/suite_test.go
Labels: C:x/leverage, T:Performance, A:Automerge

#1280 test: re-enaable ibctransfer wrapper test suite
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
  x/ibctransfer/keeper/keeper_test.go
  x/ibctransfer/keeper/util_test.go
Labels: A:Automerge

#1374 feat: price-feeder telemetry standard
  price-feeder/CHANGELOG.md
  price-feeder/oracle/filter.go
  price-feeder/oracle/oracle.go
  price-feeder/oracle/provider/binance.go
  price-feeder/oracle/provider/bitget.go
  price-feeder/oracle/provider/coinbase.go
  price-feeder/oracle/provider/gate.go
  price-feeder/oracle/provider/huobi.go
  price-feeder/oracle/provider/kraken.go
  price-feeder/oracle/provider/okx.go
  price-feeder/oracle/provider/provider.go
  price-feeder/oracle/provider/telemetry.go
Labels: A:Automerge, T:Metrics, C:Price-Feeder

#1367 feat: improve CI workflow
  .github/workflows/build.yml
  .github/workflows/simulations.yml
  .github/workflows/tests.yml
  .gitignore
  Makefile
  contrib/scripts/download-mainnet-umeed.sh
  contrib/scripts/process_genesis.sh
  contrib/scripts/single-node.sh
  contrib/scripts/tinker-mainnet-genesis.sh
  contrib/scripts/umeemainnet_fork.sh
  umee.e2e.Dockerfile
Labels: T:CI, T:Dev UX

#1378 fix: configurator setup
  app/app.go
Labels: T:Bug, C:Core

#1383 fix: remove potential panic on *MsgCreateClient.String
  CHANGELOG.md
  ante/ante_test.go
  ante/fee.go
Labels: T:Bug, A:Automerge

#1385 chore: update v1.1-v3.0 upgrade plan name
  CHANGELOG.md
  app/upgrades.go
  contrib/scripts/umeemainnet_fork.sh
Labels: A:Automerge

#1339 feat(price-feeder): add mexc provider
  price-feeder/CHANGELOG.md
  price-feeder/README.md
  price-feeder/config/config.go
  price-feeder/go.mod
  price-feeder/oracle/oracle.go
  price-feeder/oracle/provider/mexc.go
  price-feeder/oracle/provider/mexc_test.go
  price-feeder/oracle/provider/provider.go
  price-feeder/oracle/types/errors.go
  util/coin/dec.go
Labels: A:Automerge, C:Price-Feeder, S:backport/price-feeder/v0.3.x

#1393 chore: update price-feeder example config
  price-feeder/price-feeder.example.toml
Labels: A:Automerge, C:Price-Feeder

#1390 fix: set version for the base app
  app/app.go
Labels: T:Bug, A:Automerge, C:Core

#1392 feat: update ci exported genesis
  .github/workflows/tests.yml
  contrib/scripts/download-mainnet-umeed.sh
  contrib/scripts/tinker-mainnet-genesis.sh
  contrib/scripts/umeemainnet_fork.sh
Labels: T:CI, A:Automerge

#1395 feat: require compile-time flag to enable liquidator query
  CHANGELOG.md
  Makefile
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/keeper/suite_test.go
  x/leverage/types/errors.go
Labels: C:x/leverage, A:Automerge

#1401 feat: increase free oracle gas limit to 140k
  CHANGELOG.md
  ante/fee.go
Labels: A:Automerge, C:Core

#1397 fix: buf cosmos-sdk version
  proto/buf.lock
Labels: T:Bug, T:Dependencies

#1407 fix: revert: fix: buf cosmos-sdk version (#1397)
  proto/buf.lock
Labels: A:Automerge

#1370 docs: leverage proto docs update
  Makefile
  proto/umee/leverage/v1/leverage.proto
  swagger/swagger.yaml
  x/leverage/types/leverage.pb.go
Labels: A:Automerge, C:Docs

#1391 fix: general oracle improvements and ABCI determinism
  x/oracle/abci.go
  x/oracle/keeper/ballot.go
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
  x/oracle/types/expected_keeper.go
  x/oracle/types/utils_test.go
Labels: A:Automerge, C:x/oracle

#1405 fix: MinCollateralLiquidity validation
  CHANGELOG.md
  x/leverage/types/token.go
Labels: C:x/leverage, A:Automerge

#1371 chore: add atom to default registry
  app/test_helpers.go
  starport.ci.yml
  x/leverage/client/tests/suite.go
  x/leverage/fixtures/params.go
  x/leverage/fixtures/token.go
  x/leverage/gov_handler_test.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/keeper/suite_test.go
  x/leverage/simulation/operations_test.go
  x/leverage/types/genesis.go
  x/leverage/types/params.go
  x/leverage/types/token.go
  x/oracle/keeper/hooks_test.go
  x/oracle/types/asset.go
  x/oracle/types/params.go
Labels: A:Automerge

#1421 feat: set migrations orders
  app/app.go
  contrib/scripts/umeemainnet_fork.sh
Labels: C:x/leverage, A:Automerge, C:x/oracle

#1418 perf(ante/fee): optimize requiredFees calculation
  ante/fee.go
Labels: T:Performance

#1404 docs: release notes draft
  CHANGELOG.md
  RELEASE_NOTES.md
  ante/fee.go
  ante/fee_test.go
  app/params/app_settings.go
  app/test_helpers.go
  cmd/umeed/cmd/app_creator.go
  tests/e2e/e2e_setup_test.go
  util/sim/deliver.go
  x/oracle/client/tests/suite.go
Labels: A:Automerge, C:Docs

#1433 fix: RewardBallotWinners determinism
  x/oracle/abci.go
  x/oracle/keeper/reward.go
  x/oracle/keeper/reward_test.go
Labels: T:Bug, A:Automerge, C:x/oracle

#1432 fix: oracle.RewardBallotWinner detect duplicated uumee
  util/genmap/list.go
  x/oracle/keeper/reward.go
  x/oracle/keeper/reward_unit_test.go
Labels: T:Bug, A:Automerge, C:x/oracle

#1435 chore: update gravity bridge
  go.mod
  go.sum
Labels: T:Dependencies, A:Automerge

#1427 docs: update release notes
  CHANGELOG.md
  RELEASE_NOTES.md
Labels: C:Docs

#1444 fix: fix the github workflow for upgrade
  contrib/scripts/download-mainnet-umeed.sh
  contrib/scripts/umeemainnet_fork.sh
  contrib/scripts/upgrade-test-single-node.sh
Labels: A:Automerge

#1453 docs: v3.0.1 release notes
  RELEASE_NOTES.md
Labels: A:Automerge, C:Docs

#1460 fix: update & fix gravity bridge
  CHANGELOG.md
  RELEASE_NOTES.md
  go.mod
  go.sum
Labels: T:Dependencies
