Repository umee-network/umee, pull requests merged in 2023-02, with the labels that each got.

#1776 fix: correct ICS20 middleware handlers
  app/app.go
  x/uibc/quota/ibc_module.go
Labels: A:Automerge, C:IBC

#1779 fix: increase pricefeeder e2e test timeout
  tests/e2e/e2e_setup_test.go
Labels: T:Test, A:Automerge

#1777 feat: helper function to emit events
  util/sdkutil/events.go
  x/leverage/keeper/interest.go
  x/leverage/keeper/msg_server.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/reserves.go
  x/oracle/abci.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
  x/oracle/keeper/msg_server.go
  x/uibc/quota/ibc_module.go
Labels: A:Automerge, C:Core

#1780 chore: move sdkutil coin functions to the coin package
  util/coin/coin.go
  util/sdkutil/coin.go
  x/leverage/keeper/borrows_test.go
  x/leverage/keeper/collateral_test.go
  x/leverage/keeper/exchange_rate_test.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/keeper/interest_test.go
  x/leverage/keeper/invariants_test.go
  x/leverage/keeper/iter_test.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/msg_server.go
  x/leverage/keeper/msg_server_test.go
  x/leverage/keeper/oracle_test.go
  x/leverage/keeper/reserves_test.go
  x/leverage/keeper/suite_test.go
Labels: T:Test, A:Automerge, C:Core

#1786 chore: bump cosmos-sdk/math
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1788 fix: deprecated use of sdkerrors
  app/upgrades.go
  util/checkers/proposal.go
  x/incentive/errors.go
  x/incentive/msgs.go
  x/leverage/keeper/exchange_rate.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/token.go
  x/leverage/types/errors.go
  x/leverage/types/genesis.go
  x/leverage/types/msgs.go
  x/leverage/types/token.go
  x/oracle/keeper/historic_price.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/msg_server.go
  x/oracle/types/errors.go
  x/oracle/types/msgs.go
  x/oracle/types/msgs_test.go
  x/uibc/errors.go
  x/uibc/ics20/keeper/keeper.go
  x/uibc/msg.go
  x/uibc/quota/ibc_module.go
  x/uibc/quota/keeper/quota.go
  x/uibc/quota/keeper/relay.go
Labels: A:Automerge

#1787 chore: remove rc upgrade handlers
  app/upgrades.go
Labels: A:Automerge, C:Core

#1792 chore: fix the deprecated sdkerrors in price-feeder
  price-feeder/go.mod
  price-feeder/oracle/types/errors.go
Labels: A:Automerge

#1772 chore: add 4.1 upgrade handler
  ante/spam_prevention_test.go
  app/upgrades.go
  x/oracle/keeper/msg_server_test.go
Labels: A:Automerge

#1771 test: add experimental e2e tests on docker image
  .github/workflows/tests.yml
  Makefile
  contrib/images/umee.e2e.dockerfile
  price-feeder/oracle/client/tx.go
  tests/grpc/client/tx/sign.go
  x/uibc/msg_test.go
Labels: T:Test, A:Automerge

#1794 chore: Updating Cosmos SDK to 0.46.9 and Tendermint to 0.34.26
  RELEASE_NOTES.md
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: T:Dependencies, A:Automerge

#1800 fix: intercase leverage fix
  CHANGELOG.md
  proto/umee/leverage/v1/query.proto
  swagger/swagger.yaml
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/oracle_test.go
  x/leverage/types/query.pb.go
Labels: A:Automerge, S:backport/v4.0.x

#1802 feat: register v4.0.1 upgrade
  app/upgrades.go
Labels: A:Automerge, S:backport/v4.0.x

#1806 chore: using AvgPrice for denom to check ibc-transfer quota
  app/app.go
  x/oracle/keeper/historic_price.go
  x/uibc/expected_keepers.go
  x/uibc/quota/keeper/grpc_query_test.go
  x/uibc/quota/keeper/keeper.go
  x/uibc/quota/keeper/quota.go
Labels: A:Automerge

#1811 chore: simplify upgrades
  app/upgrades.go
Labels: A:Automerge

#1815 chore: update upgrades and mergify to v4.1
  .mergify.yml
  app/upgrades.go
Labels: A:Automerge

#1812 fix: collateral share restriction works during partial price outages
  CHANGELOG.md
  x/leverage/keeper/collateral.go
  x/leverage/keeper/msg_server_test.go
  x/leverage/keeper/oracle_test.go
  x/leverage/keeper/suite_test.go
  x/leverage/types/expected_types.go
Labels: C:x/leverage, S:backport/v4.1.x

#1807 fix: 4.1 BNB migration
  CHANGELOG.md
  app/upgrades.go
  x/leverage/keeper/internal_test.go
  x/leverage/keeper/migrations.go
  x/leverage/keeper/suite_test.go
  x/leverage/types/errors.go
  x/oracle/keeper/migrations.go
Labels: T:Bug, C:x/leverage, A:Automerge, C:x/oracle, S:backport/v4.1.x

#1808 feat: automatically clear unsupplied blacklisted tokens
  CHANGELOG.md
  x/leverage/README.md
  x/leverage/keeper/msg_server.go
  x/leverage/keeper/token.go
Labels: C:x/leverage, S:backport/v4.1.x

#1823 fix: bnb migration
  app/upgrades.go
  x/leverage/keeper/migrations.go
  x/leverage/types/errors.go
  x/oracle/keeper/migrations.go
Labels: T:Bug, A:Automerge, S:backport/v4.1.x

#1825 fix: skip BNB migration instead of error if no BNB denom present
  x/leverage/keeper/migrations.go
Labels: C:x/leverage, A:Automerge, S:backport/v4.1.x

#1821 fix!: allow safe leverage operations during partial oracle outages
  CHANGELOG.md
  proto/umee/leverage/v1/query.proto
  swagger/swagger.yaml
  x/leverage/client/tests/tests.go
  x/leverage/keeper/borrows.go
  x/leverage/keeper/collateral.go
  x/leverage/keeper/errors.go
  x/leverage/keeper/errors_test.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/keeper/iter.go
  x/leverage/keeper/keeper.go
  x/leverage/keeper/limits.go
  x/leverage/keeper/liquidate.go
  x/leverage/keeper/msg_server.go
  x/leverage/keeper/oracle.go
  x/leverage/keeper/oracle_test.go
  x/leverage/keeper/outage_test.go
  x/leverage/types/query.pb.go
Labels: C:x/leverage, A:Automerge, C:x/oracle, S:backport/v4.1.x

#1833 fix: plan name for rc2 binary
  app/upgrades.go
Labels: T:Bug

#1835 test: use experimental for default CI tests
  .github/workflows/tests.yml
Labels: T:Test, T:CI, A:Automerge

#1839 chore: bump sdk
  go.mod
  go.sum
  price-feeder/go.mod
  price-feeder/go.sum
Labels: A:Automerge, C:Core

#1843 chore(ci): update mergify config for the merge-queue
  .mergify.yml
Labels: T:CI

#1845 fix: getting bonded validator power in oracle endblocker
  CHANGELOG.md
  tests/e2e/e2e_setup_test.go
  tests/e2e/e2e_test.go
  x/oracle/abci.go
  x/oracle/abci_test.go
Labels: S:backport/v4.1.x

#1846 chore: add 4.1.0-rc3 migration
  app/upgrades.go
Labels: S:backport/v4.1.x

#1850 chore: update upgrades structure
  app/upgrades.go
Labels: C:Core

#1851 fix: ballot sorting
  x/oracle/types/ballot.go
  x/oracle/types/ballot_test.go
Labels: C:x/oracle, S:backport/v4.1.x

#1852 fix(oracle): power vote calculation
  x/oracle/abci.go
  x/oracle/abci_test.go
  x/oracle/keeper/ballot.go
  x/oracle/keeper/params.go
  x/oracle/simulations/genesis.go
  x/oracle/types/params.go
  x/oracle/types/params_test.go
Labels: T:Bug, C:x/oracle, S:backport/v4.1.x

#1856 chore: refactor the test
  app/test_helpers.go
  app/upgradev3/min_commission_test.go
  price-feeder/config/config_test.go
  price-feeder/go.mod
  price-feeder/go.sum
  tests/simulation/sim_test.go
  tests/simulation/state.go
  util/bytes_test.go
  util/decmath/decmath_test.go
  util/genmap/genmap_test.go
  x/leverage/client/tests/cli_test.go
  x/leverage/keeper/errors_test.go
  x/leverage/keeper/liquidate_test.go
  x/leverage/keeper/math_test.go
  x/leverage/types/genesis_test.go
  x/leverage/types/keys_test.go
  x/leverage/types/queries_test.go
  x/leverage/types/token_test.go
  x/oracle/client/tests/cli_test.go
  x/oracle/keeper/genesis_test.go
  x/oracle/keeper/reward_unit_test.go
  x/oracle/types/ballot_test.go
  x/oracle/types/codec_test.go
  x/oracle/types/denom_test.go
  x/oracle/types/hash_test.go
  x/oracle/types/keys_test.go
  x/oracle/types/msgs_test.go
  x/oracle/types/params_test.go
  x/oracle/types/vote_test.go
Labels: A:Automerge

#1865 chore(uibc): update quota -> outflows
  proto/umee/uibc/v1/genesis.proto
  proto/umee/uibc/v1/query.proto
  x/uibc/client/cli/query.go
  x/uibc/client/tests/cli_test.go
  x/uibc/client/tests/query_test.go
  x/uibc/genesis.go
  x/uibc/genesis.pb.go
  x/uibc/genesis_test.go
  x/uibc/keys.go
  x/uibc/module/abci.go
  x/uibc/query.pb.go
  x/uibc/query.pb.gw.go
  x/uibc/quota/keeper/genesis.go
  x/uibc/quota/keeper/grpc_query.go
  x/uibc/quota/keeper/grpc_query_test.go
  x/uibc/quota/keeper/quota.go
  x/uibc/quota/keeper/quota_test.go
Labels: C:IBC

#1867 feat: add register token info base_denom
  CHANGELOG.md
  proto/umee/leverage/v1/query.proto
  x/leverage/client/cli/query.go
  x/leverage/client/tests/tests.go
  x/leverage/keeper/grpc_query.go
  x/leverage/keeper/grpc_query_test.go
  x/leverage/types/query.pb.go
  x/leverage/types/query.pb.gw.go
Labels: C:x/leverage

#1813 docs(oracle): clarify slash window
  x/oracle/README.md
Labels: A:Automerge

#1793 feat: incentive module KVstore and structs
  proto/umee/incentive/v1/genesis.proto
  proto/umee/incentive/v1/incentive.proto
  proto/umee/incentive/v1/query.proto
  util/store/store.go
  x/incentive/errors.go
  x/incentive/genesis.go
  x/incentive/genesis.pb.go
  x/incentive/keeper/keeper.go
  x/incentive/keeper/keys.go
  x/incentive/keeper/store.go
  x/incentive/keys.go
  x/incentive/query.pb.go
Labels: C:x/incentive

#1875 feat: incentive module msg and query framework
  proto/umee/incentive/v1/query.proto
  swagger/swagger.yaml
  x/incentive/client/cli/query.go
  x/incentive/client/cli/tx.go
  x/incentive/codec.go
  x/incentive/keeper/grpc_query.go
  x/incentive/keeper/msg_server.go
  x/incentive/keeper/params.go
  x/incentive/query.pb.go
  x/incentive/query.pb.gw.go
Labels: C:x/incentive
